# Check out https://docs.codemagic.io/yaml/yaml/ for more information

workflows:
    flutter-package:
        name: Flutter or Dart Package
        environment:
            flutter: stable
        scripts:
            - flutter packages pub get
            - flutter test
